"""add usda_id to foods

Revision ID: b6bcacdd7538
Revises: a2eb20f2d3c5
Create Date: 2025-02-15 00:13:52.973047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bcacdd7538'
down_revision = 'a2eb20f2d3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usda_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['usda_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('usda_id')

    # ### end Alembic commands ###
